const translations = {
    en: {
        page1: "Home Page",
        page2: "Pupuke & Rangitoto",
        page3: "Ngāti Pāoa & Waitematā",
        subtitle: "Satellite Site",
        hero_text1: "Our Vision",
        hero_text2: "To create a rich, collaborative culture that unites kura (schools), pouako (teachers), ākonga (students) and whānau to work collectively on common goals for the benefit of all.",
        source_title: "Sources page",
        learn_more: "Learn More",
        pupuke: "Lake Pupuke",
        rangitoto: "Rangitoto Island",
        pupuke_paragraph: "Lake Pupuke traditionally known in Māori as Pupukemoana is a heart-shaped freshwater lake occupying a volcanic crater (or maar) situated to the east of Westlake Boys High School. The heart shape is a result of its formation by the linking of two circular craters - a larger one forming most of the lake and a smaller one forming the arm in the northeast. Separated from the sea by less than 200 m at one point, it has a circumference of about 4.5 km and reaches 57m in depth. It is popular for recreational activities and the lake front property around it.",
        geology1_paragraph: "Other similar craters in the Auckland volcanic field were either buried by later eruptions or breached by erosion as rainwater collected and overflowed the edge of the crater. Lake Pupuke remains a lake because, unlike the other vents, its eruptions produced substantial lava flows; water can thus escape through cracks in the lava reaching under the crater wall, creating a series of freshwater springs along the beaches between Takapuna and Milford. The lava flow at the end of Takapuna Beach enveloped a kauri forest, producing an internationally significant collection of tree moulds, which has been called 'New Zealand's only example of a fossil forest preserved in a lava flow' and which 'ranks among the best examples in the world.' Some moulds have escaped burial by the boat ramp and car park built on top of the lava and can be viewed at low tide.",
        legend_paragraph: "A traditional Māori legend surrounding the lake tells of a tupua couple, children of the fire gods. After quarreling and cursing Mahuika, the fire-goddess, their home on the mainland was destroyed by Matahoe, god of earthquakes and eruptions, on Mahuika's behalf. Lake Pupuke resulted from the destruction, while Rangitoto Island rose from the sea as their exile. The mists surrounding Rangitoto at certain times are considered the tears of the tupua couple for their former home.",
        humans_paragraph: "Close to the Takapuna city centre, the lake is popular not only with wild birds (such as shags) but with picnickers, paddlers, kayakers, rowers, yachtsmen, divers, and windsurfers (lessons have been given on the lake). Free divers (no tanks) have practiced in the lake. College rowing crews use it. There have been boating races. and the Pupuke Boating Club operates there. Takapuna Boating Club hosts regattas. The Auckland Dragon Boat Association runs an annual regionals race event on the lake, with 200m, 500m and 2 km races. The lake is the venue for Dragon Boat, Canoe sprints, Canoe marathon, and Waka Ama sprint racing within the Canoe Competition at the World Masters Games 2017 held in Auckland. Lake Pupuke is suitable for swimming but is murky and contains thick vegetation, and there have been drownings. The lake has been tested for bacteria and generally meets safe swimming conditions.",
        rangitoto_paragraph: "Rangitoto Island is a volcanic island in the Hauraki Gulf. The 5.5 km (3.4 mi) wide island is a symmetrical shield volcano cone, reaching a height of 260 m (850 ft). Rangitoto is the youngest and largest of the approximately 50 volcanoes of the Auckland volcanic field, having formed in an eruption about 600 years ago, and covering an area of 2,311 ha (5,710 acres). It is separated from the mainland of Auckland's North Shore by the Rangitoto Channel. Since World War II, it has been linked by a causeway to the much older, non-volcanic Motutapu Island. Rangitoto is Māori for 'Bloody Sky', with the name coming from the full phrase Ngā Rangi-i-totongia-a Tama-te-kapua ('The days of the bleeding of Tama-te-kapua'). Tama-te-kapua was the captain of the Arawa waka (canoe) and was badly wounded on the island, after having lost a battle with the Tainui iwi (tribe) at Islington Bay.",
        association_paragraph: "The volcano erupted within the historical memory of the local Māori iwi (tribes). Human footprints have been found between layers of Rangitoto volcanic ash on the adjoining Motutapu Island. Ngāi Tai was the iwi living on Motutapu, and considers both islands their ancestral home. Ngāti Paoa also has links with Rangitoto.",
        geology2_paragraph: "Rangitoto was formed during a single phase of eruptions that may have lasted only 5-10 years, about 600 years ago. Previous inferences that it was formed by a series of eruptions commencing at least 6000 years ago[7] have been disproved by the most recent research. The first part of the eruption was wet and produced surges of volcanic ash that mantles neighbouring Motutapu Island. The later part of the eruption was dry and built most of Rangitoto, erupting all the lava flows and scoria cones at the apex. The 2.3 km3 (0.55 cu mi) of material that erupted from the volcano was about equal to the combined mass produced by all the previous eruptions in the Auckland volcanic field, which were spread over more than 200,000 years.",
        volcanic_paragraph: "In 2013, scientists from Auckland University said new studies showed Rangitoto had been much more active in the past than previously thought, suggesting it had been active on and off for around 1000 years before the final eruptions around 550 years ago (BP= before 1950). In February 2014 a 150 m (490 ft) deep hole was drilled through the western flank of Rangitoto. The same group of university scientists declared that it revealed a long history of spasmodic eruptions going back at least 6000 years, although the bulk of activity post-dated 650 years. Civil Defence officials said the discovery did not make living in Auckland any more dangerous, but did change their view of how an eruption might proceed. These headline-grabbing results have been controversial and not accepted by all geologists. n 2018, most of the original group of Auckland University geologists reported on their latest research and reinterpretation of the drillhole sequence and pronounced that the island did not erupt off and on prior to its major eruption about 600 years ago and is not a unique polygenetic volcano in the monogenetic Auckland volcanic field, as they had previously inferred. While it is possible that Rangitoto buried one or more smaller volcanoes, to date there is no strong evidence to support this idea.",
        features_paragraph: "Subsidence back down the throat during the cooling process has left a moat-like ring around the crater summit, which may be viewed from a path which goes right round the rim and up to the highest point. In some parts of the island, fields of clinker-like black lava stones are exposed, appearing very recent to a casual eye. About 200 metres from the top of the mountain on the eastern side visitors can walk through some of about seven known lava tubes — tubes left behind after the passage of liquid lava. The more accessible of the caves are signposted. Lava tubes are formed when low-viscosity molten lava known as pahoehoe flows and cools on the outside due to contact with the ground and air, to form a hard crust allowing the still-liquid molten lava to continue to flow through inside. At Rangitoto the large tubes are cave-like. A torch is needed to explore the caves. The longest known cave is about 50 m long.",
        ngati_paragraph: "Ngāti Pāoa is a Māori iwi of the Hauraki region. Its traditional lands stretch from the western side of the Hauraki Plains to Auckland. They also settled on Hauraki Gulf islands such as Waiheke. Ngāti Pāoa is one of five tribes of the Marutūāhu confederation, the others being Ngāti Maru, Ngāti Rongoū, Ngāti Tamaterā and Ngāti Whanaunga. The Marutūāhu tribes are all descended from Marutūāhu, a son of Hotunui, who is said to have arrived in New Zealand on the Tainui canoe. The Marutūāhu tribes are therefore part of the Tainui group of tribes. The Marutūāhu confederation is also part of the Hauraki collective of tribes.",
        early_paragraph: "Ngāti Pāoa is descended from Pāoa. According to a Hauraki tradition his father was Rongo-tiu-moe-whara of the East Coast iwi, Ngāti Kahungunu, born at Whai-a-pāoa near Wharekahika. According to Tainui accounts his father was Hekemaru, his paternal grandparents were Pikiao from the Te Arawa tribe, and Rereiao, a high-born Waikato woman descended from Whatihua, and he was the brother of Mahuta, from whom Ngāti Mahuta is descended. On either version, Pāoa lived with his first wife Tauhākari, sons Toapoto and Toawhana, and daughter Koura at Kaitotehe, near Taupiri in the central Waikato. Pāoa moved from Kaitotehe to Hauraki, where he married Tukutuku, a granddaughter of Tamaterā, with whom he had sons, first Haora Tipa Koinaki and second Horowhenua.",
        family_paragraph: "Pāoa and Tukutuku's children lived in and around the Hauraki Plains. Ngāti Pāoa later spread to the western side of the Firth of Thames, from where they also frequented the Hunua Ranges. By the 1700s they also frequented the Tāmaki (Auckland) isthmus, the North Shore and the eastern and northern Coromandel Peninsula. In about 1780 Ngāti Pāoa established settlements along the western side of the Tamaki River and at Mokoia (present-day Panmure). In 1790 and from 1793 to 1798 they engaged in many battles with tribes to the north, at least as far as the Mahurangi district. By 1805 they were tiring of war and negotiated peace settlements with many neighbouring tribes. At this time they had settlements along the Tamaki River as far as Otahuhu.",
        waitemata_paragraph: "Waitematā Harbour is the main access by sea to Auckland. For this reason it is often referred to as Auckland Harbour, despite the fact that it is one of two harbours adjoining the city. The harbour forms the northern and eastern coasts of the Auckland isthmus and is crossed by the Auckland Harbour Bridge. It is matched on the southern side of the city by the shallower waters of the Manukau Harbour. With an area of 70 square miles (180 km2), it connects the city's main port and the Auckland waterfront to the Hauraki Gulf and the Pacific Ocean. It is sheltered from Pacific storms by Auckland's North Shore, Rangitoto Island, and Waiheke Island.",
        etymology_paragraph: "The oldest Māori name of the harbour was Te Whanga-nui o Toi (The Big Bay of Toi), named after Toi, an early Māori explorer. The name Waitematā means 'Te Mata Waters', which according to some traditions refers to a mauri stone (a stone of Māori religious significance) called Te Mata, which was placed on Boat Rock (in the harbour south-west of Chatswood) by Te Arawa chief Kahumatamomoe. A popular translation of Waitematā is 'The Obsidian Waters', referring to obsidian rock (matā). Another popular translation, derived from this, is 'The Sparkling Waters', as the harbour waters were said to glint like the volcanic glass obsidian. However, this is incorrect, as grammatically Waitematā could not mean this.",
        history_paragraph: "Prior to European settlement, the harbour was the site of many Tāmaki Māori pā and kāinga, including Kauri Point in Chatswood, Okā at Point Erin, Te Tō at Freemans Bay, Te Ngahuwera, Te Rerenga-oraiti at Point Britomart, and Ōrākei. Herald Island and Watchmen Island were both settled by the Waiohua confederation. The Waitematā Harbour was traditionally used as a fishery used by Tāmaki Māori for sharks and snapper. In the late 18th century and early 19th century, the waters were fished together by Ngāti Whātua-o-Ōrākei and Ngāti Pāoa. In traditional legend, the Waitematā Harbour is protected by a taniwha named Ureia, who takes the form of a whale. The harbour has long been the main anchorage and port area for the Auckland region. Well-sheltered not only by the Hauraki Gulf itself but also by Rangitoto Island, the harbour offered good protection in almost all winds, and lacked dangerous shoals or major sand bars (like on the Manukau Harbour) that would have made entry difficult. The harbour also proved a fertile area for encroaching development, with major land reclamation undertaken, especially along the Auckland waterfront, within a few decades of the city's European founding.",
        canal_paragraph: "Taking the idea of the several Māori portage paths over the isthmus one step further, the creation of a canal that would link the Waitematā and Manukau harbours was considered in the early 1900s. Legislation (the Auckland and Manukau Canal Act 1908) was passed that would allow authorities to take privately owned land where it was deemed required for a canal. However, no serious work (or land take) was undertaken. The act was repealed on 1 November 2010.",
        contact_us: "Contact Us",
        source_info: "Source Info"
    },
    mi: {
        page1: "Whārangi Kāinga",
        page2: "Pupuke me Rangitoto",
        page3: "Ngāti Pāoa me Waitematā",
        subtitle: "Paetukutuku ā-Whetū",
        hero_text1: "To Tatou Matakite",
        hero_text2: "Ki te hanga i tetahi ahurea whai kiko, mahi tahi e whakakotahi ai nga kura, nga kaiako, nga tauira me nga whanau ki te mahi tahi i runga i nga whaainga kotahi hei painga mo te katoa.",
        source_title: "Whārangi Puna",
        learn_more: "Ako atu",
        pupuke: "Roto Pupuke",
        rangitoto: "Te Moutere o Rangitoto",
        pupuke_paragraph: "Ko te roto o Pupuke e mohiotia ana i mua i te reo Maori ko Pupukemoana he roto wai maori te ahua ngakau e noho ana i te rua puia (maar ranei) kei te taha rawhiti o te Kura Tuarua o Westlake Boys. Ko te ahua o te ngakau ko te hua o tona hanganga na te hono o nga rua porohita porohita - he nui ake te nuinga o te roto me tetahi mea iti hei ringa ki te raki-ma-raki. Ka wehea mai i te moana ma te iti iho i te 200 m i te waahi kotahi, he 4.5 kiromita tona porowhita, ka eke ki te 57m te hohonu. He rongonui mo nga mahi whakangahau me nga taonga o mua o te roto.",
        geology1_paragraph: "Ko ētahi atu māra ōrite i te papa puia o Ākarana i tanumia e nga hūnga ā muri ake, i pakaru rānei i te horo i te kohikohitanga o te wai marangai, a, ka waipuke i te tapa o te whare tapere. Ka noho roto tonu a Roto Pupuke nā te mea, ehara i ērā atu haora, he nui tonu te rere o ōna hūnga; Mā te wai e mawhiti ai i roto i nga whāwhā i roto i te lava e tae ana ki raro i te pakitara whare tapere, e waihanga ana i tētahi rangatū o nga puna wai maori i nga one i waenganui o Takapuna me Milford. Na te rere o te lava i te mutunga o Takapuna Beach i pūhera he ngahere kauri, e hanga ana i tētahi kohinga nui o ngā ritenga rākau o te ao whānui, kua kiia nei ko 'te tauira anake o aotearoa o tētahi ngahere fossil e tiakina ana i roto i tētahi rerenga lava' ā, ko tērā 'e noho ana i waenganui i ngā tauira tino pai i te ao.' Kua mawhiti ētahi ritenga i te tanumanga i te poti me te pāka motokā i hangaia ki runga i te lava, ā, ka taea te tirotiro i te tai hahaka.",
        legend_paragraph: "Ko te poutohu Māori tūturu e karapoti ana i te roto e kōrero ana ki tētahi tokorua tupu, he tamariki na nga atua ahi. I muri iho i te tautohetohe me te kanga i a Mahuika, ka ngaro to rātau kāinga i runga i te tuawhenua e Matahoe, te atua o nga rū me te hū, mō Mahuika. Na te Roto Pupuke i hua mai i te whakangaromanga, i te wā e whakatika ana a Rangitoto i te moana hei manene mo rātau. I ētahi wā e whakaarotia ana ko nga hē e karapoti ana i a Rangitoto nga roimata o te tokorua tupua mo to rāua kāinga o mua.",
        humans_paragraph: "E tata ana ki te pokapū o te taone o Takapuna, ehara te roto i te mea e manakohia ana ki ngā manu mohoao anake (pēnei i te shags) engari me ngā pūkohu, ngā pātiki, ngā kayakers, ngā haupae, ngā yachtsmen, ngā momo, me ngā hau (kua hoatu ki runga i te roto). Kua whakamātauria e nga momo wātea (kāore he reheke) i roto i te roto. Ka whakamahia e nga kaimahi haupae kāreti. Tērā nga iwi poti. a, e mahi ana te Karapu Pupuke Boating i reira. Ko nga mano o Takapuna Boating Club. Ko te Pānga o Ākarana Tarakona e whakahaere ana i tētahi takahanga whakataetae ā-rohe ā-tau i runga i te roto, me te 200m, e 500m me te 2 km iwi. Ko te roto te wāhi mo Tarakona Boat, Canoe sprints, Canoe marahana, me Waka Ama e tā ana i roto i te Whakataetae Canoe i ngā Tākaro Matua o te Ao 2017 i puritia i Ākarana. He pai te Roto Pupuke mo te kaukau, engari he māngere, a, he mātotoru te whakawhāititanga, a, he toremi. Kua whakamātauria te roto mo te huakita, a, ko te nuinga o te wā e tūtaki ana ki nga āhuatanga kaukau haumaru.",
        rangitoto_paragraph: "He motu puia te Motu o Rangitoto i te Kōwhiti o Hauraki. Ko te motu whānui e 5.5 km (3.4 mi) he puia whakangungu hangarite, tae atu ki te tiketike o te 260 m (850 ft). Ko Rangitoto te pōtiki me te nui rawa atu o ngā puia tata ki te 50 o te papa puia o Ākarana, kua hangaia i roto i te hūnga tata ki te 600 tau ki mua, ā, e hipa ana i tētahi wāhi e 2,311 ha (5,710 eka). E wehea ana i te tuawhenua o te Shore ki te Raki o Ākarana e te Hongere Rangitoto. Mai i te Pakanga Ii o te Ao, kua honoa e tētahi huarahi ki te Motu o Motu o Motutapu, kāore i te mōhiotia. Kei te Māori a Rangitoto mō 'Bloody Sky', me te ingoa e haere mai ana i te kīanga katoa o Ngā Rangi-i-totongia-a Tama-te-kapua ('Ko ngā rā o te toto o Tama-te-kapua'). Ko Tama-te-kapua te kāpene o te Arawa waka (canoe) a, i tino mamae i runga i te motu, i muri i te ngarotanga o te pakanga ki te iwi o Tainui (tribe) i Islington Bay.",
        association_paragraph: "Ka hū te puia ki roto i te pūmahara hītori o te iwi Māori o te rohe (ngā iwi). Kua kitea nga tapuwae tangata i waenganui i nga apa puia o Rangitoto i te Motu o Motutapu pātata. Ko Ngāi Tai te iwi e noho ana i Motutapu, a, e whakaaro ana ki nga moutere e rua to rātau kāinga tupuna. He hononga anō hoki a Ngāti Paoa ki Rangitoto.",
        geology2_paragraph: "I hangaia a Rangitoto i te wā kotahi o te hūnga tērā pea e 5-10 tau noa iho, tata ki te 600 tau ki mua. Ko ngā mōhiotanga o mua i hangaia e tētahi rangatū hū e tīmata ana i te 6000 tau ki mua[7] kua whakakāhoretia e te rangahau o nā noa nei. Ko te wāhi tuatahi o te hū, he mākū, a, i puta mai he pātōtō puia e noho tata ana ki Te Motu o Motutapu. I maroke te wāhi o muri o te hū, a, i hangaia te nuinga o Rangitoto, e hū ana i nga rere katoa o te lava me te scoria i te moka. Ko te 2.3 km3 (0.55 cu mi) o ngā rawa i hū mai i te puia, e ōrite ana ki te tokomaha paheko i hangaia e ngā hūnga o mua i te āpure puia o Ākarana, neke atu i te 200,000 tau.",
        features_paragraph: "I te wā o te tukanga whakamātao, kua mahue i te āhua o te korokoro i te wā o te tukanga whakamātao tētahi rīngi pēnei i te tihi o te whare tapere, tērā pea ka tirohia mai i tētahi ara e haere tika ana i te rim, tae atu ki te wāhi tiketike rawa. I ētahi wāhi o te motu, ka puta mai ngā āpure pōhatu lava pango pēnei i te clinker, e puta ana i mua tata nei ki te whatu wairangi. Tata ki te 200 mita mai i te tihi o te maunga i te taha ki te rāwhiti ka taea e nga manuhiri te haere i ētahi o ngā ngongo lava e whitu e mōhiotia ana — he ngongo e mahue ana i muri i te haerenga o te lava wai. Ko te nui ake o te āheitanga o nga ana e tohu ana. Ka hangaia ngā ngongo Lava ina mōhiotia te lava whakarewa iti e mōhiotia ana ko te rere pahoehoe me te mātao i waho nā te whakapā atu ki te whenua me te hau, ki te hanga i tētahi kirinuku uaua e āhei ai te lava whakarewa tonu kia rere tonu ki roto. I Rangitoto he rite tonu nga ngongo nui. E hiahiatia ana he rama hai hōpara i nga ana. Tata ki te 50 m te roa o te ana e mōhiotia ana.",
        ngati_paragraph: "Ko Ngāti Pāoa tētahi iwi Māori o te rohe Hauraki. Ko ōna whenua tūturu e whārōrō ana mai i te taha ki te uru o nga Hauraki Plains ki Ākarana. I noho hoki rātau i runga i nga moutere o hauraki Gulf pērā i Waiheke. Ko Ngāti Pāoa tētahi o ngā iwi e rima o te whakakotahitanga o Marutūāhu, ko ētahi atu ko Ngāti Maru, ko Ngāti Rongoū, ko Ngāti Tamaterā me Ngāti Whanaunga. Kua heke katoa nga iwi o Marutūāhu i Marutūāhu, he tama na Hotunui, e kiia ana kua tae mai ki Aotearoa i runga i te waka Tainui. Koia nga iwi o Marutūāhu he wāhi o te rōpū Tainui o nga iwi. He wāhanga anō hoki te whakakotahitanga o Marutūāhu no te huihuinga o Hauraki o nga iwi.",
        early_paragraph: "Kua heke iho a Ngāti Pāoa i Pāoa. E ai ki tētahi tikanga Hauraki ko tōna pāpā ko Rongo-tiu-moe-whara o te iwi o Te Tairāwhiti, ko Ngāti Kahungunu, i whānau mai i Whai-a-pāoa tata ki Wharekahika. E ai ki nga kaute a Tainui ko Tona papa ko Hekemaru, ko ona tīpuna paternal ko Pikiao no te iwi o Te Arawa, ko Rereiao, he wahine Waikato whanau i heke iho i Whatihua, a ko ia te teina o Mahuta, i heke iho ai a Ngāti Mahuta. I runga i tētahi putanga, ka noho a Pāoa me tana wahine tuatahi ko Tauhākari, he tama ko Toapoto raua ko Toawhana, me tana tamāhine ko Koura i Kaitotehe, e tata ana ki Taupiri i waikato matua. I neke atu a Pāoa i Kaitotehe ki Hauraki, i reira ia i mārena ai ki Tukutuku, he mokopuna nui no Tamaterā, he tama tāna, ko Haora Tipa Koinaki me te tuarua o Horowhenua.",
        family_paragraph: "I noho nga tamariki a Pāoa rāua ko Tukutuku i roto i nga Hauraki Plains. I muri iho ka hora atu a Ngāti Pāoa ki te taha ki te uru o te Firth of Thames, mai i te wāhi i auautia ai hoki e rātau nga Awhe Hunua. Tae noa ki nga tau kotahi rau e waru tekau mā rua, ka auautia hoki e rātau te Tāmaki (Auckland), te Shore ki te Raki me te Takiwā o Coromandel ki te raki. Tata ki te 1780 ngā kāinga i whakatūria e Ngāti Pāoa i te taha ki te uru o te Awa o Tamaki, i Mokoia (te Panmure rā). I te tau 1790, mai i te 1793 ki te 1798, he maha nga whawhai ki nga iwi ki te raki, ki te takiwā o Mahurangi. Tae noa ki te tau kotahi mano e waru tekau mā rua, ka whawhai rātau, a, ka whakaritea he kāinga rangimārie me nga iwi hoa noho tata. I tēnei wā he kāinga rātau i te Awa o Tamaki ki Otahuhu.",
        waitemata_paragraph: "Ko Waitematā Whanga te urunga matua ma te moana ki Ākarana. Nā tēnei take i kiia ai ko Ākarana Whanga, ahakoa ko tētahi o ngā aka e rua e pātata ana ki te taone. Ko te aka he hanga i nga rohe ki te raki, ki te rāwhiti hoki o Ākarana, a, e rīpekatia ana e te Arawhiti Whanga o Ākarana. E ōrite ana ki te taha ki te tonga o te taone, ma nga wai pāpaku o te Whanga o Manukau. Mā tētahi wāhi e 70 ngā māwhiti tapawhā (180 km2), ka tūhono i te tauranga matua o te taone me te wai o Ākarana ki te Kōwhiti Hauraki me te Moana nui ā Kiwa. E whakarurutia ana i nga āwhā o Te Moana nui ā Kiwa i te Taha ki te Raki o Ākarana, i Te Motu o Rangitoto, i Te Motu o Waiheke.",
        etymology_paragraph: "Ko te ingoa Māori tawhito rawa o te aka ko Te Whanga-nui o Toi (The Big Bay of Toi), i tapaina ki Toi, he kaitoro Māori o mua. Ko te tikanga o te ingoa o Waitematā ko 'Te Mata Waters', e pā ana ki ētahi tikanga e pā ana ki tētahi pōhatu mauri (he pōhatu Māori tikanga whakapono) e kiia nei ko Te Mata, i whakatakotoria ki Boat Rock (i te taha ki te tonga-uru o Chatswood) e Te Arawa ariki Kahumatamoe. Ko te whakawhitinga kaingākautia o Waitematā ko 'The Obsidian Waters', e pā ana ki te toka obsidian (matā). Ko tētahi atu whakawhitinga e paingia ana, i takea mai i tēnei, ko 'The Sparkling Waters', e kīa ana ko nga wai aka kia rite ki te karaehe puia. Heoi anō, he hē tēnei, nā te mea kāore i taea e Waitematā wetereo te tikanga o tēnei.",
        history_paragraph: "I mua i te kāinga o Ūropi, ko te aka te wāhi o te tokomaha o Tāmaki Māori pā me te kāinga, tae atu ki Kauri Point i Chatswood, Okā i Point Erin, Te Tō i Freemans Bay, Te Ngahuwera, Te Rerenga-oraiti i Point Britomart, me Ōrākei. I whakataua rāua tahi e te motu o Waiohua, te Motu o Herald me te Motu o Watchmen. I whakamahia noatia te Whanga Waitematā hai hī ika i whakamahia e Tāmaki Māori mo te mangō me te hopu. I te mutunga o te rau tau 18 me te rau tau 19, ka hī ika tahitia nga wai e Ngāti Whātua-o-Ōrākei me Ngāti Pāoa. I roto i te poutohu tūturu, ka parea te Whanga Waitematā e tētahi taniwha ko Ureia te ingoa, e mau ana i te āhua o te tohorā. Ko te aka te wāhi matua me te wāhi tauranga mo te rohe o Ākarana. Ehara i te mea nā te Kōwhiti Hauraki anake, engari na Te Motu o Rangitoto, i tukuna e te aka he parenga pai i roto i ngā hau katoa, ā, kāore i a ia ngā shoals mōrearea, ngā pae kirikiri nui rānei (pēnei i te Whanga Manukau) tērā pea ka uaua te tāurunga. I kitea hoki e te aka he wāhi mōmona mo te whanaketanga encroaching, me te nui o te whenua e mahia ana, i te taha o te wai o Ākarana, i roto i ētahi tau ruarua o te kitenga o Ūropi o te taone.",
        canal_paragraph: "Mā te mau i te ariā mo ngā ara tauranga maha Māori i runga i te āhua o te kotahi hipanga, ko te hanganga o tētahi awa e hono ana i ngā whanga Waitematā me Manukau i whakaarotia i te tōmua o nga tau kotahi rau e waru tekau mā rua. I tukuna te ture (te Ture Ākarana me Manukau Canal 1908) e āhei ai ngā mana ki te tango i tētahi whenua tūmataiti i reira i whakaarotia ai e hiahiatia ana mō tētahi awa. Heoi anō, kaore he mahi nui (he take whenua rānei) i mahia. I whakakoretia te mahi i te 1 o Whiringa 2010.",
        contact_us: "Whakapā Mai",
        source_info: "Puna Pārongo"
    }
};

function switchLanguage(language) {
    const elementsToTranslate = [
        { selector: '.page1', translationKey: 'page1' },
        { selector: '.page2', translationKey: 'page2' },
        { selector: '.page3', translationKey: 'page3' },
        { selector: '.subtitle', translationKey: 'subtitle' },
        { selector: '.hero_text1', translationKey: 'hero_text1' },
        { selector: '.hero_text2', translationKey: 'hero_text2' },
        { selector: '.source_title', translationKey: 'source_title' },
        { selector: '.learn_more1', translationKey: 'learn_more' },
        { selector: '.pupuke', translationKey: 'pupuke' },
        { selector: '.rangitoto', translationKey: 'rangitoto' },
        { selector: '.pupuke_paragraph', translationKey: 'pupuke_paragraph' },
        { selector: '.geology1_paragraph', translationKey: 'geology1_paragraph' },
        { selector: '.legend_paragraph', translationKey: 'legend_paragraph' },
        { selector: '.humans_paragraph', translationKey: 'humans_paragraph' },
        { selector: '.rangitoto_paragraph', translationKey: 'rangitoto_paragraph' },
        { selector: '.association_paragraph', translationKey: 'association_paragraph' },
        { selector: '.geology2_paragraph', translationKey: 'geology2_paragraph' },
        { selector: '.volcanic_paragraph', translationKey: 'volcanic_paragraph' },
        { selector: '.features_paragraph', translationKey: 'features_paragraph' },
        { selector: '.ngati_paragraph', translationKey: 'ngati_paragraph' },
        { selector: '.early_paragraph', translationKey: 'early_paragraph' },
        { selector: '.family_paragraph', translationKey: 'family_paragraph' },
        { selector: '.waitemata_paragraph', translationKey: 'waitemata_paragraph' },
        { selector: '.etymology_paragraph', translationKey: 'etymology_paragraph' },
        { selector: '.history_paragraph', translationKey: 'history_paragraph' },
        { selector: '.canal_paragraph', translationKey: 'canal_paragraph' },
        { selector: '.learn_more2', translationKey: 'learn_more' },
        { selector: '.learn_more3', translationKey: 'learn_more' },
        { selector: '.learn_more4', translationKey: 'learn_more' },
        { selector: '#button-1 .text', translationKey: 'contact_us' },
        { selector: '#button-2 .text', translationKey: 'source_info' },
    ];

    elementsToTranslate.forEach(item => {
        const element = document.querySelector(item.selector);
        if (element) {
            element.textContent = translations[language][item.translationKey];
        } else {
            console.log(`Element with selector '${item.selector}' not found.`);
        }
    });

    const h1Tag = document.querySelector('.rangitoto_island');
    if (h1Tag) {
        if (language === "mi") {
            h1Tag.style.transform = "translateX(10%)";
        } else {
            h1Tag.style.transform = "translateX(37%)";
        }
    }

    localStorage.setItem("language", language);
}

function setRadioInput(language) {
    const radioInputs = document.querySelectorAll('input[name="radio"]');
    radioInputs.forEach(input => {
        if (input.value === language) {
            input.checked = true;
        }
    });
}

document.querySelectorAll('input[name="radio"]').forEach(input => {
    input.addEventListener('change', function() {
        switchLanguage(this.value);
    });
});

window.onload = function() {
    const savedLanguage = localStorage.getItem("language") || "en";
    switchLanguage(savedLanguage);
    setRadioInput(savedLanguage);
};